;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :see)

(eval-when (:compile-toplevel :load-toplevel :execute)
 (progn
   (cffi:define-foreign-library libcvc
    (:darwin (:or "libcvc.0.dylib" "libcvc.dylib"))
    (:unix (:or "libcvc.so.0.1" "libcvc.so"))
    (:windows "libcvc.dll")
    (t "libcvc"))
   (cffi:use-foreign-library libcvc)))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'cl-swig-lispify)
    (cl:defun cl-swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        (constant "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))



;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (cl:&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cffi:defcfun ("cv_open_cv_version" #.(cl-swig-lispify "cv_open_cv_version" 'function)) :string)

(cffi:defcenum #.(cl-swig-lispify "CvError" 'enumname)
	(#.(cl-swig-lispify "NO_ERROR" 'enumvalue :keyword) #.0)
	(#.(cl-swig-lispify "CV_ERROR" 'enumvalue :keyword) #.-1)
	(#.(cl-swig-lispify "STD_ERROR" 'enumvalue :keyword) #.-2)
	(#.(cl-swig-lispify "UNKNOWN_ERROR" 'enumvalue :keyword) #.-3)
	(#.(cl-swig-lispify "OTHER_ERROR" 'enumvalue :keyword) #.1))

(cffi:defcstruct #.(cl-swig-lispify "CvEnum" 'classname)
	(#.(cl-swig-lispify "name" 'slotname) :string)
	(#.(cl-swig-lispify "value" 'slotname) :int))

(cffi:defcfun ("cv_get_error_message" #.(cl-swig-lispify "cv_get_error_message" 'function)) :string)

(cffi:defcfun ("cv_get_error_code" #.(cl-swig-lispify "cv_get_error_code" 'function)) :int)

(cffi:defcfun ("cv_set_error" #.(cl-swig-lispify "cv_set_error" 'function)) :int
  (code :int)
  (msg :string))

(cffi:defcfun ("cv_clear_error" #.(cl-swig-lispify "cv_clear_error" 'function)) :void)

(cffi:defcfun ("cv_strings_new" #.(cl-swig-lispify "cv_strings_new" 'function)) :int
  (out_new_strings :pointer))

(cffi:defcfun ("cv_strings_new_with_data" #.(cl-swig-lispify "cv_strings_new_with_data" 'function)) :int
  (count :int)
  (data :pointer)
  (out_new_strings :pointer))

(cffi:defcfun ("cv_strings_add" #.(cl-swig-lispify "cv_strings_add" 'function)) :int
  (self :pointer)
  (string :string))

(cffi:defcfun ("cv_strings_free" #.(cl-swig-lispify "cv_strings_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_strings_count" #.(cl-swig-lispify "cv_strings_count" 'function)) :int
  (self :pointer)
  (out_count :pointer))

(cffi:defcfun ("cv_strings_get" #.(cl-swig-lispify "cv_strings_get" 'function)) :int
  (self :pointer)
  (idx :int)
  (out_string :pointer))

(cffi:defcfun ("cv_buffer_new" #.(cl-swig-lispify "cv_buffer_new" 'function)) :int
  (out_new_buffer :pointer))

(cffi:defcfun ("cv_buffer_new_with_data" #.(cl-swig-lispify "cv_buffer_new_with_data" 'function)) :int
  (size :int)
  (data :pointer)
  (out_new_buffer :pointer))

(cffi:defcfun ("cv_buffer_free" #.(cl-swig-lispify "cv_buffer_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_buffer_size" #.(cl-swig-lispify "cv_buffer_size" 'function)) :int
  (self :pointer)
  (out_size :pointer))

(cffi:defcfun ("cv_buffer_data" #.(cl-swig-lispify "cv_buffer_data" 'function)) :int
  (self :pointer)
  (data :pointer))

(cffi:defcfun ("cv_floats_new" #.(cl-swig-lispify "cv_floats_new" 'function)) :int
  (out_new_floats :pointer))

(cffi:defcfun ("cv_float_new_with_data" #.(cl-swig-lispify "cv_float_new_with_data" 'function)) :int
  (size :int)
  (data :pointer)
  (out_new_floats :pointer))

(cffi:defcfun ("cv_floats_free" #.(cl-swig-lispify "cv_floats_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_floats_count" #.(cl-swig-lispify "cv_floats_count" 'function)) :int
  (self :pointer)
  (out_count :pointer))

(cffi:defcfun ("cv_floats_add" #.(cl-swig-lispify "cv_floats_add" 'function)) :int
  (self :pointer)
  (val :float))

(cffi:defcfun ("cv_floats_get" #.(cl-swig-lispify "cv_floats_get" 'function)) :int
  (self :pointer)
  (idx :int)
  (out_value :pointer))

(cffi:defcfun ("cv_floats_data" #.(cl-swig-lispify "cv_floats_data" 'function)) :int
  (self :pointer)
  (out_data :pointer))

(cffi:defcfun ("cv_doubles_new" #.(cl-swig-lispify "cv_doubles_new" 'function)) :int
  (out_new_doubles :pointer))

(cffi:defcfun ("cv_doubles_new_with_data" #.(cl-swig-lispify "cv_doubles_new_with_data" 'function)) :int
  (size :int)
  (data :pointer)
  (out_new_doubles :pointer))

(cffi:defcfun ("cv_doubles_free" #.(cl-swig-lispify "cv_doubles_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_doubles_count" #.(cl-swig-lispify "cv_doubles_count" 'function)) :int
  (self :pointer)
  (out_size :pointer))

(cffi:defcfun ("cv_doubles_add" #.(cl-swig-lispify "cv_doubles_add" 'function)) :int
  (self :pointer)
  (val :double))

(cffi:defcfun ("cv_doubles_get" #.(cl-swig-lispify "cv_doubles_get" 'function)) :int
  (self :pointer)
  (idx :int)
  (out_value :pointer))

(cffi:defcfun ("cv_doubles_data" #.(cl-swig-lispify "cv_doubles_data" 'function)) :int
  (self :pointer)
  (out_data :pointer))

(cffi:defcfun ("cv_ints_new" #.(cl-swig-lispify "cv_ints_new" 'function)) :int
  (out_new_ints :pointer))

(cffi:defcfun ("cv_ints_new_with_data" #.(cl-swig-lispify "cv_ints_new_with_data" 'function)) :int
  (count :int)
  (data :pointer)
  (out_new_ints :pointer))

(cffi:defcfun ("cv_ints_free" #.(cl-swig-lispify "cv_ints_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_ints_count" #.(cl-swig-lispify "cv_ints_count" 'function)) :int
  (self :pointer)
  (out_size :pointer))

(cffi:defcfun ("cv_ints_add" #.(cl-swig-lispify "cv_ints_add" 'function)) :int
  (self :pointer)
  (val :int))

(cffi:defcfun ("cv_ints_get" #.(cl-swig-lispify "cv_ints_get" 'function)) :int
  (self :pointer)
  (idx :int)
  (out_value :pointer))

(cffi:defcfun ("cv_ints_data" #.(cl-swig-lispify "cv_ints_data" 'function)) :int
  (self :pointer)
  (out_data :pointer))

(cffi:defcfun ("cv_scalar_new" #.(cl-swig-lispify "cv_scalar_new" 'function)) :int
  (a :double)
  (b :double)
  (c :double)
  (d :double)
  (out_scalar :pointer))

(cffi:defcfun ("cv_scalar_copy" #.(cl-swig-lispify "cv_scalar_copy" 'function)) :int
  (self :pointer)
  (out_scalar :pointer))

(cffi:defcfun ("cv_scalar_free" #.(cl-swig-lispify "cv_scalar_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_scalar_data" #.(cl-swig-lispify "cv_scalar_data" 'function)) :int
  (self :pointer)
  (out_data :pointer))

(cffi:defcfun ("cv_size_new" #.(cl-swig-lispify "cv_size_new" 'function)) :int
  (w :float)
  (h :float)
  (out_new_size :pointer))

(cffi:defcfun ("cv_size_copy" #.(cl-swig-lispify "cv_size_copy" 'function)) :int
  (self :pointer)
  (out_new_size :pointer))

(cffi:defcfun ("cv_size_free" #.(cl-swig-lispify "cv_size_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_size_width" #.(cl-swig-lispify "cv_size_width" 'function)) :int
  (self :pointer)
  (out_width :pointer))

(cffi:defcfun ("cv_size_height" #.(cl-swig-lispify "cv_size_height" 'function)) :int
  (self :pointer)
  (out_height :pointer))

(cffi:defcfun ("cv_point_new" #.(cl-swig-lispify "cv_point_new" 'function)) :int
  (x :float)
  (y :float)
  (out_new_point :pointer))

(cffi:defcfun ("cv_point_copy" #.(cl-swig-lispify "cv_point_copy" 'function)) :int
  (self :pointer)
  (out_new_point :pointer))

(cffi:defcfun ("cv_point_free" #.(cl-swig-lispify "cv_point_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_point_x" #.(cl-swig-lispify "cv_point_x" 'function)) :int
  (self :pointer)
  (out_x :pointer))

(cffi:defcfun ("cv_point_y" #.(cl-swig-lispify "cv_point_y" 'function)) :int
  (self :pointer)
  (out_y :pointer))

(cffi:defcfun ("cv_points_new" #.(cl-swig-lispify "cv_points_new" 'function)) :int
  (out_new_points :pointer))

(cffi:defcfun ("cv_points_new_with_data" #.(cl-swig-lispify "cv_points_new_with_data" 'function)) :int
  (count :int)
  (data :pointer)
  (out_new_points :pointer))

(cffi:defcfun ("cv_points_add" #.(cl-swig-lispify "cv_points_add" 'function)) :int
  (self :pointer)
  (point :pointer))

(cffi:defcfun ("cv_points_free" #.(cl-swig-lispify "cv_points_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_points_count" #.(cl-swig-lispify "cv_points_count" 'function)) :int
  (self :pointer)
  (out_count :pointer))

(cffi:defcfun ("cv_points_get" #.(cl-swig-lispify "cv_points_get" 'function)) :int
  (self :pointer)
  (idx :int)
  (out_point :pointer))

(cffi:defcfun ("cv_rect_new" #.(cl-swig-lispify "cv_rect_new" 'function)) :int
  (x :float)
  (y :float)
  (w :float)
  (h :float)
  (out_new_rect :pointer))

(cffi:defcfun ("cv_rect_copy" #.(cl-swig-lispify "cv_rect_copy" 'function)) :int
  (self :pointer)
  (out_new_rect :pointer))

(cffi:defcfun ("cv_rect_free" #.(cl-swig-lispify "cv_rect_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_rect_x" #.(cl-swig-lispify "cv_rect_x" 'function)) :int
  (self :pointer)
  (out_x :pointer))

(cffi:defcfun ("cv_rect_y" #.(cl-swig-lispify "cv_rect_y" 'function)) :int
  (self :pointer)
  (out_y :pointer))

(cffi:defcfun ("cv_rect_width" #.(cl-swig-lispify "cv_rect_width" 'function)) :int
  (self :pointer)
  (out_width :pointer))

(cffi:defcfun ("cv_rect_height" #.(cl-swig-lispify "cv_rect_height" 'function)) :int
  (self :pointer)
  (out_height :pointer))

(cffi:defcfun ("cv_rotated_rect_new" #.(cl-swig-lispify "cv_rotated_rect_new" 'function)) :int
  (x :float)
  (y :float)
  (width :float)
  (height :float)
  (angle :float)
  (out_new_rr :pointer))

(cffi:defcfun ("cv_rotated_rect_copy" #.(cl-swig-lispify "cv_rotated_rect_copy" 'function)) :int
  (self :pointer)
  (out_new_rr :pointer))

(cffi:defcfun ("cv_rotated_rect_free" #.(cl-swig-lispify "cv_rotated_rect_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_x" #.(cl-swig-lispify "cv_rotated_rect_x" 'function)) :int
  (self :pointer)
  (out_x :pointer))

(cffi:defcfun ("cv_rotated_rect_y" #.(cl-swig-lispify "cv_rotated_rect_y" 'function)) :int
  (self :pointer)
  (out_y :pointer))

(cffi:defcfun ("cv_rotated_rect_width" #.(cl-swig-lispify "cv_rotated_rect_width" 'function)) :int
  (self :pointer)
  (out_width :pointer))

(cffi:defcfun ("cv_rotated_rect_height" #.(cl-swig-lispify "cv_rotated_rect_height" 'function)) :int
  (self :pointer)
  (out_height :pointer))

(cffi:defcfun ("cv_rotated_rect_angle" #.(cl-swig-lispify "cv_rotated_rect_angle" 'function)) :int
  (self :pointer)
  (out_angle :pointer))

(cffi:defcfun ("cv_rotated_rect_points" #.(cl-swig-lispify "cv_rotated_rect_points" 'function)) :int
  (self :pointer)
  (out_new_points :pointer))

(cffi:defcfun ("cv_rotated_rects_new" #.(cl-swig-lispify "cv_rotated_rects_new" 'function)) :int
  (out_new_rr :pointer))

(cffi:defcfun ("cv_rotated_rects_new_with_data" #.(cl-swig-lispify "cv_rotated_rects_new_with_data" 'function)) :int
  (count :int)
  (data :pointer)
  (out_new_rr :pointer))

(cffi:defcfun ("cv_rotated_rects_add" #.(cl-swig-lispify "cv_rotated_rects_add" 'function)) :int
  (self :pointer)
  (rect :pointer))

(cffi:defcfun ("cv_rotated_rects_free" #.(cl-swig-lispify "cv_rotated_rects_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_rotated_rects_count" #.(cl-swig-lispify "cv_rotated_rects_count" 'function)) :int
  (self :pointer)
  (out_count :pointer))

(cffi:defcfun ("cv_rotated_rects_get" #.(cl-swig-lispify "cv_rotated_rects_get" 'function)) :int
  (self :pointer)
  (idx :int)
  (out_ref_rect :pointer))

(cffi:defcvar ("cv_depth_enum" #.(cl-swig-lispify "cv_depth_enum" 'variable))
 :pointer)

(cffi:defcfun ("cv_mats_new" #.(cl-swig-lispify "cv_mats_new" 'function)) :int
  (out_new_mats :pointer))

(cffi:defcfun ("cv_mats_new_copy" #.(cl-swig-lispify "cv_mats_new_copy" 'function)) :int
  (mats :pointer)
  (out_new_mats :pointer))

(cffi:defcfun ("cv_mats_new_with_data" #.(cl-swig-lispify "cv_mats_new_with_data" 'function)) :int
  (count :int)
  (data :pointer)
  (out_new_mats :pointer))

(cffi:defcfun ("cv_mats_add" #.(cl-swig-lispify "cv_mats_add" 'function)) :int
  (self :pointer)
  (mat :pointer))

(cffi:defcfun ("cv_mats_free" #.(cl-swig-lispify "cv_mats_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_mats_count" #.(cl-swig-lispify "cv_mats_count" 'function)) :int
  (self :pointer)
  (out_count :pointer))

(cffi:defcfun ("cv_mats_get" #.(cl-swig-lispify "cv_mats_get" 'function)) :int
  (self :pointer)
  (i :int)
  (out_mat_ref :pointer))

(cffi:defcfun ("cv_make_type" #.(cl-swig-lispify "cv_make_type" 'function)) :int
  (depth :int)
  (channels :int)
  (out_type :pointer))

(cffi:defcfun ("cv_type_depth" #.(cl-swig-lispify "cv_type_depth" 'function)) :int
  (type :int)
  (out_depth :pointer))

(cffi:defcfun ("cv_type_channels" #.(cl-swig-lispify "cv_type_channels" 'function)) :int
  (type :int)
  (out_channels :pointer))

(cffi:defcfun ("cv_mat_new" #.(cl-swig-lispify "cv_mat_new" 'function)) :int
  (out_new_mat :pointer))

(cffi:defcfun ("cv_mat_new_copy" #.(cl-swig-lispify "cv_mat_new_copy" 'function)) :int
  (self :pointer)
  (out_new_mat :pointer))

(cffi:defcfun ("cv_mat_new_with_scalar" #.(cl-swig-lispify "cv_mat_new_with_scalar" 'function)) :int
  (shape :pointer)
  (type :int)
  (scalar :pointer)
  (out_new_mat :pointer))

(cffi:defcfun ("cv_mat_new_with_data" #.(cl-swig-lispify "cv_mat_new_with_data" 'function)) :int
  (shape :pointer)
  (type :int)
  (data :pointer)
  (out_new_mat :pointer))

(cffi:defcfun ("cv_mat_new_with_roi" #.(cl-swig-lispify "cv_mat_new_with_roi" 'function)) :int
  (source :pointer)
  (roi :pointer)
  (out_new_mat :pointer))

(cffi:defcfun ("cv_mat_free" #.(cl-swig-lispify "cv_mat_free" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_mat_empty" #.(cl-swig-lispify "cv_mat_empty" 'function)) :int
  (self :pointer)
  (out_value :pointer))

(cffi:defcfun ("cv_mat_copy_to" #.(cl-swig-lispify "cv_mat_copy_to" 'function)) :int
  (self :pointer)
  (dst :pointer))

(cffi:defcfun ("cv_mat_copy_to_with_mask" #.(cl-swig-lispify "cv_mat_copy_to_with_mask" 'function)) :int
  (self :pointer)
  (dst :pointer)
  (mask :pointer))

(cffi:defcfun ("cv_mat_convert_to" #.(cl-swig-lispify "cv_mat_convert_to" 'function)) :int
  (self :pointer)
  (dst :pointer)
  (type :int)
  (alpha :double)
  (beta :double))

(cffi:defcfun ("cv_mat_reshape" #.(cl-swig-lispify "cv_mat_reshape" 'function)) :int
  (self :pointer)
  (cn :int)
  (shape :pointer)
  (out_mat :pointer))

(cffi:defcfun ("cv_mat_patch_nans" #.(cl-swig-lispify "cv_mat_patch_nans" 'function)) :int
  (self :pointer)
  (val :double))

(cffi:defcfun ("cv_mat_mean" #.(cl-swig-lispify "cv_mat_mean" 'function)) :int
  (self :pointer)
  (out_scalar :pointer))

(cffi:defcfun ("cv_mat_lut" #.(cl-swig-lispify "cv_mat_lut" 'function)) :int
  (self :pointer)
  (lut :pointer)
  (dst :pointer))

(cffi:defcfun ("cv_mat_rows" #.(cl-swig-lispify "cv_mat_rows" 'function)) :int
  (self :pointer)
  (out_rows :pointer))

(cffi:defcfun ("cv_mat_cols" #.(cl-swig-lispify "cv_mat_cols" 'function)) :int
  (self :pointer)
  (out_cols :pointer))

(cffi:defcfun ("cv_mat_channels" #.(cl-swig-lispify "cv_mat_channels" 'function)) :int
  (self :pointer)
  (out_channels :pointer))

(cffi:defcfun ("cv_mat_depth" #.(cl-swig-lispify "cv_mat_depth" 'function)) :int
  (self :pointer)
  (out_depth :pointer))

(cffi:defcfun ("cv_mat_type" #.(cl-swig-lispify "cv_mat_type" 'function)) :int
  (self :pointer)
  (out_type :pointer))

(cffi:defcfun ("cv_mat_elem_size" #.(cl-swig-lispify "cv_mat_elem_size" 'function)) :int
  (self :pointer)
  (out_size :pointer))

(cffi:defcfun ("cv_mat_step" #.(cl-swig-lispify "cv_mat_step" 'function)) :int
  (self :pointer)
  (out_step :pointer))

(cffi:defcfun ("cv_mat_is_continuous" #.(cl-swig-lispify "cv_mat_is_continuous" 'function)) :int
  (self :pointer)
  (out_continuous :pointer))

(cffi:defcfun ("cv_mat_total" #.(cl-swig-lispify "cv_mat_total" 'function)) :int
  (self :pointer)
  (out_total :pointer))

(cffi:defcfun ("cv_mat_dims" #.(cl-swig-lispify "cv_mat_dims" 'function)) :int
  (self :pointer)
  (out_dims :pointer))

(cffi:defcfun ("cv_mat_size" #.(cl-swig-lispify "cv_mat_size" 'function)) :int
  (self :pointer)
  (out_size :pointer))

(cffi:defcfun ("cv_mat_get_ptr" #.(cl-swig-lispify "cv_mat_get_ptr" 'function)) :int
  (m :pointer)
  (idx :pointer)
  (out_ptr :pointer))

(cffi:defcfun ("cv_get_tick_count" #.(cl-swig-lispify "cv_get_tick_count" 'function)) :int
  (out_count :pointer))

(cffi:defcfun ("cv_get_tick_frequency" #.(cl-swig-lispify "cv_get_tick_frequency" 'function)) :int
  (out_freq :pointer))

(cffi:defcfun ("cv_extract_channel" #.(cl-swig-lispify "cv_extract_channel" 'function)) :int
  (src :pointer)
  (dst :pointer)
  (coi :int))

(cffi:defcfun ("cv_merge" #.(cl-swig-lispify "cv_merge" 'function)) :int
  (channels :pointer)
  (out_mat :pointer))

(cffi:defcfun ("cv_mat_add_mat" #.(cl-swig-lispify "cv_mat_add_mat" 'function)) :int
  (mat :pointer)
  (addendum :pointer))

(cffi:defcfun ("cv_mat_add_scalar" #.(cl-swig-lispify "cv_mat_add_scalar" 'function)) :int
  (mat :pointer)
  (addendum :pointer))

(cffi:defcfun ("cv_mat_mul_const" #.(cl-swig-lispify "cv_mat_mul_const" 'function)) :int
  (mat :pointer)
  (multiplier :double))

(cffi:defcfun ("cv_mat_dot" #.(cl-swig-lispify "cv_mat_dot" 'function)) :int
  (self :pointer)
  (m :pointer)
  (out :pointer))

(cffi:defcvar ("cv_imread_modes_enum" #.(cl-swig-lispify "cv_imread_modes_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_imread_flags_enum" #.(cl-swig-lispify "cv_imread_flags_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_imwrite_flags_enum" #.(cl-swig-lispify "cv_imwrite_flags_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_imwrite_exr_type_flags_enum" #.(cl-swig-lispify "cv_imwrite_exr_type_flags_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_imwrite_png_flags_enum" #.(cl-swig-lispify "cv_imwrite_png_flags_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_imwrite_pam_flags_enum" #.(cl-swig-lispify "cv_imwrite_pam_flags_enum" 'variable))
 :pointer)

(cffi:defcfun ("cv_imread" #.(cl-swig-lispify "cv_imread" 'function)) :int
  (filename :string)
  (flags :int)
  (out_img :pointer))

(cffi:defcfun ("cv_imread_multi" #.(cl-swig-lispify "cv_imread_multi" 'function)) :int
  (filename :string)
  (mats :pointer)
  (flags :int))

(cffi:defcfun ("cv_imdecode" #.(cl-swig-lispify "cv_imdecode" 'function)) :int
  (buf :pointer)
  (flags :int)
  (out_img :pointer))

(cffi:defcfun ("cv_imwrite" #.(cl-swig-lispify "cv_imwrite" 'function)) :int
  (filename :string)
  (img :pointer)
  (params :pointer))

(cffi:defcfun ("cv_imencode" #.(cl-swig-lispify "cv_imencode" 'function)) :int
  (file_ext :string)
  (img :pointer)
  (params :pointer)
  (out_buffer :pointer))

(cffi:defcfun ("cv_have_image_reader" #.(cl-swig-lispify "cv_have_image_reader" 'function)) :int
  (filename :string)
  (out_result :pointer))

(cffi:defcfun ("cv_have_image_writer" #.(cl-swig-lispify "cv_have_image_writer" 'function)) :int
  (filename :string)
  (out_result :pointer))

(cffi:defcvar ("cv_line_types_enum" #.(cl-swig-lispify "cv_line_types_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_hershey_fonts_enum" #.(cl-swig-lispify "cv_hershey_fonts_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_color_conversion_codes_enum" #.(cl-swig-lispify "cv_color_conversion_codes_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_interpolation_flags_enum" #.(cl-swig-lispify "cv_interpolation_flags_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_interpolation_warp_enum" #.(cl-swig-lispify "cv_interpolation_warp_enum" 'variable))
 :pointer)

(cffi:defcfun ("cv_cvt_color" #.(cl-swig-lispify "cv_cvt_color" 'function)) :int
  (src :pointer)
  (dst :pointer)
  (code :int)
  (dstCn :int))

(cffi:defcfun ("cv_blur" #.(cl-swig-lispify "cv_blur" 'function)) :int
  (src :pointer)
  (dst :pointer)
  (ksize :pointer)
  (anchor :pointer)
  (borderType :int))

(cffi:defcfun ("cv_resize" #.(cl-swig-lispify "cv_resize" 'function)) :int
  (src :pointer)
  (dst :pointer)
  (dsize :pointer)
  (fx :double)
  (fy :double)
  (interpolation :int))

(cffi:defcfun ("cv_line" #.(cl-swig-lispify "cv_line" 'function)) :int
  (img :pointer)
  (pt1 :pointer)
  (pt2 :pointer)
  (color :pointer)
  (thickness :int)
  (line_type :int)
  (shift :int))

(cffi:defcfun ("cv_arrowed_line" #.(cl-swig-lispify "cv_arrowed_line" 'function)) :int
  (img :pointer)
  (pt1 :pointer)
  (pt2 :pointer)
  (color :pointer)
  (thickness :int)
  (line_type :int)
  (shift :int)
  (tipLength :double))

(cffi:defcfun ("cv_circle" #.(cl-swig-lispify "cv_circle" 'function)) :int
  (img :pointer)
  (center :pointer)
  (radius :int)
  (color :pointer)
  (thickness :int)
  (lineType :int)
  (shift :int))

(cffi:defcfun ("cv_ellipse" #.(cl-swig-lispify "cv_ellipse" 'function)) :int
  (img :pointer)
  (center :pointer)
  (axes :pointer)
  (angle :double)
  (startAngle :double)
  (endAngle :double)
  (color :pointer)
  (thickness :int)
  (lineType :int)
  (shift :int))

(cffi:defcfun ("cv_rectangle" #.(cl-swig-lispify "cv_rectangle" 'function)) :int
  (img :pointer)
  (rect :pointer)
  (color :pointer)
  (thickness :int)
  (lineType :int)
  (shift :int))

(cffi:defcfun ("cv_get_text_size" #.(cl-swig-lispify "cv_get_text_size" 'function)) :int
  (text :string)
  (fontFace :int)
  (fontScale :double)
  (thickness :int)
  (out_baseline :pointer)
  (out_size :pointer))

(cffi:defcfun ("cv_put_text" #.(cl-swig-lispify "cv_put_text" 'function)) :int
  (img :pointer)
  (text :string)
  (org :pointer)
  (fontFace :int)
  (fontScale :double)
  (color :pointer)
  (thickness :int)
  (lineType :int)
  (bottomLeftOrigin :bool))

(cffi:defcfun ("cv_median_blur" #.(cl-swig-lispify "cv_median_blur" 'function)) :int
  (input :pointer)
  (output :pointer)
  (ksize :int))

(cffi:defcvar ("cv_mouse_event_types_enum" #.(cl-swig-lispify "cv_mouse_event_types_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_mouse_event_flags_enum" #.(cl-swig-lispify "cv_mouse_event_flags_enum" 'variable))
 :pointer)

(cffi:defcfun ("cv_named_window" #.(cl-swig-lispify "cv_named_window" 'function)) :int
  (winname :string)
  (flags :int))

(cffi:defcfun ("cv_destroy_window" #.(cl-swig-lispify "cv_destroy_window" 'function)) :int
  (winname :string))

(cffi:defcfun ("cv_destroy_all_windows" #.(cl-swig-lispify "cv_destroy_all_windows" 'function)) :int)

(cffi:defcfun ("cv_imshow" #.(cl-swig-lispify "cv_imshow" 'function)) :int
  (winname :string)
  (mat :pointer))

(cffi:defcfun ("cv_get_window_property" #.(cl-swig-lispify "cv_get_window_property" 'function)) :int
  (winname :string)
  (flag :int)
  (out_value :pointer))

(cffi:defcfun ("cv_set_window_property" #.(cl-swig-lispify "cv_set_window_property" 'function)) :int
  (winname :string)
  (flag :int)
  (value :double))

(cffi:defcfun ("cv_set_window_title" #.(cl-swig-lispify "cv_set_window_title" 'function)) :int
  (winname :string)
  (title :string))

(cffi:defcfun ("cv_wait_key" #.(cl-swig-lispify "cv_wait_key" 'function)) :int
  (delay :int)
  (out_key :pointer))

(cffi:defcfun ("cv_move_window" #.(cl-swig-lispify "cv_move_window" 'function)) :int
  (winname :string)
  (x :int)
  (y :int))

(cffi:defcfun ("cv_resize_window" #.(cl-swig-lispify "cv_resize_window" 'function)) :int
  (winname :string)
  (width :int)
  (height :int))

(cffi:defcfun ("cv_set_mouse_callback" #.(cl-swig-lispify "cv_set_mouse_callback" 'function)) :int
  (winname :string)
  (on_mouse :pointer)
  (userdata :pointer))

(cffi:defcvar ("cv_video_capture_apis_enum" #.(cl-swig-lispify "cv_video_capture_apis_enum" 'variable))
 :pointer)

(cffi:defcfun ("cv_video_capture_new" #.(cl-swig-lispify "cv_video_capture_new" 'function)) :int
  (out_capture :pointer))

(cffi:defcfun ("cv_video_capture_free" #.(cl-swig-lispify "cv_video_capture_free" 'function)) :int
  (v :pointer))

(cffi:defcfun ("cv_video_capture_open_uri" #.(cl-swig-lispify "cv_video_capture_open_uri" 'function)) :int
  (v :pointer)
  (uri :string)
  (api_preference :int))

(cffi:defcfun ("cv_video_capture_open_device" #.(cl-swig-lispify "cv_video_capture_open_device" 'function)) :int
  (v :pointer)
  (device :int)
  (api_preference :int))

(cffi:defcfun ("cv_video_capture_set" #.(cl-swig-lispify "cv_video_capture_set" 'function)) :int
  (v :pointer)
  (prop :int)
  (param :double))

(cffi:defcfun ("cv_video_capture_get" #.(cl-swig-lispify "cv_video_capture_get" 'function)) :int
  (v :pointer)
  (prop :int)
  (out_value :pointer))

(cffi:defcfun ("cv_video_capture_is_opened" #.(cl-swig-lispify "cv_video_capture_is_opened" 'function)) :int
  (v :pointer)
  (out_value :pointer))

(cffi:defcfun ("cv_video_capture_read" #.(cl-swig-lispify "cv_video_capture_read" 'function)) :int
  (v :pointer)
  (buf :pointer)
  (out_value :pointer))

(cffi:defcfun ("cv_video_capture_grab" #.(cl-swig-lispify "cv_video_capture_grab" 'function)) :int
  (v :pointer)
  (out_value :pointer))

(cffi:defcfun ("cv_video_capture_retrieve" #.(cl-swig-lispify "cv_video_capture_retrieve" 'function)) :int
  (v :pointer)
  (buf :pointer)
  (flag :int)
  (out_value :pointer))

(cffi:defcfun ("cv_video_writer_new" #.(cl-swig-lispify "cv_video_writer_new" 'function)) :int
  (out_writer :pointer))

(cffi:defcfun ("cv_video_writer_free" #.(cl-swig-lispify "cv_video_writer_free" 'function)) :int
  (vw :pointer))

(cffi:defcfun ("cv_video_writer_fourcc" #.(cl-swig-lispify "cv_video_writer_fourcc" 'function)) :int
  (c1 :char)
  (c2 :char)
  (c3 :char)
  (c4 :char)
  (out_value :pointer))

(cffi:defcfun ("cv_video_writer_open" #.(cl-swig-lispify "cv_video_writer_open" 'function)) :int
  (vw :pointer)
  (name :string)
  (fourcc :int)
  (fps :double)
  (size :pointer)
  (is_color :bool))

(cffi:defcfun ("cv_video_writer_is_opened" #.(cl-swig-lispify "cv_video_writer_is_opened" 'function)) :int
  (vw :pointer)
  (out_value :pointer))

(cffi:defcfun ("cv_video_writer_write" #.(cl-swig-lispify "cv_video_writer_write" 'function)) :int
  (vw :pointer)
  (img :pointer))

(cffi:defcvar ("cv_dnn_backend_enum" #.(cl-swig-lispify "cv_dnn_backend_enum" 'variable))
 :pointer)

(cffi:defcvar ("cv_dnn_target_enum" #.(cl-swig-lispify "cv_dnn_target_enum" 'variable))
 :pointer)

(cffi:defcfun ("cv_dnn_read_net" #.(cl-swig-lispify "cv_dnn_read_net" 'function)) :int
  (model :string)
  (config :string)
  (framework :string)
  (out_net :pointer))

(cffi:defcfun ("cv_dnn_net_free" #.(cl-swig-lispify "cv_dnn_net_free" 'function)) :int
  (net :pointer))

(cffi:defcfun ("cv_dnn_net_empty" #.(cl-swig-lispify "cv_dnn_net_empty" 'function)) :int
  (net :pointer)
  (out_value :pointer))

(cffi:defcfun ("cv_dnn_net_set_input" #.(cl-swig-lispify "cv_dnn_net_set_input" 'function)) :int
  (net :pointer)
  (blob :pointer)
  (name :string)
  (scale_factor :double)
  (mean :pointer))

(cffi:defcfun ("cv_dnn_net_forward" #.(cl-swig-lispify "cv_dnn_net_forward" 'function)) :int
  (net :pointer)
  (output_name :string)
  (out_result :pointer))

(cffi:defcfun ("cv_dnn_net_forward_layers" #.(cl-swig-lispify "cv_dnn_net_forward_layers" 'function)) :int
  (net :pointer)
  (layer_names :pointer)
  (out_result :pointer))

(cffi:defcfun ("cv_dnn_net_set_preferable_backend" #.(cl-swig-lispify "cv_dnn_net_set_preferable_backend" 'function)) :int
  (net :pointer)
  (backend :int))

(cffi:defcfun ("cv_dnn_net_set_preferable_target" #.(cl-swig-lispify "cv_dnn_net_set_preferable_target" 'function)) :int
  (net :pointer)
  (target :int))

(cffi:defcfun ("cv_dnn_net_get_perf_profile" #.(cl-swig-lispify "cv_dnn_net_get_perf_profile" 'function)) :int
  (net :pointer)
  (out_layers :pointer)
  (out_time :pointer))

(cffi:defcfun ("cv_dnn_blob_from_images" #.(cl-swig-lispify "cv_dnn_blob_from_images" 'function)) :int
  (images :pointer)
  (out_blob :pointer)
  (scale_factor :double)
  (size :pointer)
  (mean :pointer)
  (swap_rb :bool)
  (crop :bool)
  (depth :int))

(cffi:defcfun ("cv_dnn_net_get_layer_names" #.(cl-swig-lispify "cv_dnn_net_get_layer_names" 'function)) :int
  (net :pointer)
  (names :pointer))

(cffi:defcfun ("cv_dnn_net_get_layer_with_name" #.(cl-swig-lispify "cv_dnn_net_get_layer_with_name" 'function)) :int
  (net :pointer)
  (layer_name :string)
  (out_layer :pointer))

(cffi:defcfun ("cv_dnn_net_get_layer_with_id" #.(cl-swig-lispify "cv_dnn_net_get_layer_with_id" 'function)) :int
  (net :pointer)
  (layer_id :int)
  (out_layer :pointer))

(cffi:defcfun ("cv_dnn_layer_blobs" #.(cl-swig-lispify "cv_dnn_layer_blobs" 'function)) :int
  (layer :pointer)
  (out_mats :pointer))

(cffi:defcfun ("cv_dnn_layer_add_blob" #.(cl-swig-lispify "cv_dnn_layer_add_blob" 'function)) :int
  (layer :pointer)
  (blob :pointer))

(cffi:defcfun ("cv_dnn_layer_free" #.(cl-swig-lispify "cv_dnn_layer_free" 'function)) :int
  (layer :pointer))

(cffi:defcfun ("cv_dnn_layer_input_name_to_index" #.(cl-swig-lispify "cv_dnn_layer_input_name_to_index" 'function)) :int
  (layer :pointer)
  (name :string)
  (out_index :pointer))

(cffi:defcfun ("cv_dnn_layer_output_name_to_index" #.(cl-swig-lispify "cv_dnn_layer_output_name_to_index" 'function)) :int
  (layer :pointer)
  (name :string)
  (out_index :pointer))

(cffi:defcfun ("cv_dnn_layer_name" #.(cl-swig-lispify "cv_dnn_layer_name" 'function)) :int
  (layer :pointer)
  (out_name :pointer))

(cffi:defcfun ("cv_dnn_layer_type" #.(cl-swig-lispify "cv_dnn_layer_type" 'function)) :int
  (layer :pointer)
  (out_type :pointer))

(cffi:defcfun ("cv_dnn_nms_boxes" #.(cl-swig-lispify "cv_dnn_nms_boxes" 'function)) :int
  (bboxes :pointer)
  (scores :pointer)
  (score_threshold :float)
  (nms_threshold :float)
  (eta :float)
  (top_k :int)
  (out_indices :pointer))

(cffi:defcenum #.(cl-swig-lispify "CvInterpolationWarp" 'enumname)
	(#.(cl-swig-lispify "WARP_NONE" 'enumvalue :keyword) #.0)
	(#.(cl-swig-lispify "WARP_FILL_OUTLIERS" 'enumvalue :keyword) #.8)
	(#.(cl-swig-lispify "WARP_INVERSE_MAP" 'enumvalue :keyword) #.16))


