;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :see)

//;;(cffi:close-foreign-library lib)
//;;(cl:eval-when (:load-toplevel :execute)
//;;(defparameter lib (cffi:load-foreign-library "libcvc/libcvc.so.0.1")))

(eval-when (:compile-toplevel :load-toplevel :execute)
 (progn
   (cffi:define-foreign-library libcvc
    (:darwin (:or "libcvc.0.dylib" "libcvc.dylib"))
    (:unix (:or "libcvc.so.0.1" "libcvc.so"))
    (:windows "libcvc.dll")
    (t "libcvc"))
   (cffi:use-foreign-library libcvc)))
    
(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'cl-swig-lispify)
    (cl:defun cl-swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        (constant "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))




;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (cl:&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cffi:defcfun ("cv_open_cv_version" #.(cl-swig-lispify "cv_open_cv_version" 'function)) :string)

(cffi:defcfun ("cv_get_error" #.(cl-swig-lispify "cv_get_error" 'function)) :string)

(cffi:defcfun ("cv_set_error" #.(cl-swig-lispify "cv_set_error" 'function)) :void
  (msg :string))

(cffi:defcfun ("cv_clear_error" #.(cl-swig-lispify "cv_clear_error" 'function)) :void)

(cffi:defcfun ("cv_buffer_new" #.(cl-swig-lispify "cv_buffer_new" 'function)) :pointer)

(cffi:defcfun ("cv_buffer_new_with_data" #.(cl-swig-lispify "cv_buffer_new_with_data" 'function)) :pointer
  (size :int)
  (data :pointer))

(cffi:defcfun ("cv_buffer_free" #.(cl-swig-lispify "cv_buffer_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_buffer_size" #.(cl-swig-lispify "cv_buffer_size" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_buffer_data" #.(cl-swig-lispify "cv_buffer_data" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_strings_new" #.(cl-swig-lispify "cv_strings_new" 'function)) :pointer)

(cffi:defcfun ("cv_strings_new_with_data" #.(cl-swig-lispify "cv_strings_new_with_data" 'function)) :pointer
  (count :int)
  (strings :pointer))

(cffi:defcfun ("cv_strings_add" #.(cl-swig-lispify "cv_strings_add" 'function)) :pointer
  (self :pointer)
  (string :string))

(cffi:defcfun ("cv_strings_free" #.(cl-swig-lispify "cv_strings_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_strings_count" #.(cl-swig-lispify "cv_strings_count" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_strings_get" #.(cl-swig-lispify "cv_strings_get" 'function)) :string
  (self :pointer)
  (i :int))

(cffi:defcfun ("cv_ints_new" #.(cl-swig-lispify "cv_ints_new" 'function)) :pointer)

(cffi:defcfun ("cv_ints_new_with_data" #.(cl-swig-lispify "cv_ints_new_with_data" 'function)) :pointer
  (count :int)
  (data :pointer))

(cffi:defcfun ("cv_ints_free" #.(cl-swig-lispify "cv_ints_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_ints_count" #.(cl-swig-lispify "cv_ints_count" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_ints_add" #.(cl-swig-lispify "cv_ints_add" 'function)) :pointer
  (self :pointer)
  (val :int))

(cffi:defcfun ("cv_ints_get" #.(cl-swig-lispify "cv_ints_get" 'function)) :int
  (self :pointer)
  (i :int))

(cffi:defcfun ("cv_ints_data" #.(cl-swig-lispify "cv_ints_data" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_floats_new" #.(cl-swig-lispify "cv_floats_new" 'function)) :pointer)

(cffi:defcfun ("cv_floats_new_with_data" #.(cl-swig-lispify "cv_floats_new_with_data" 'function)) :pointer
  (size :int)
  (data :pointer))

(cffi:defcfun ("cv_floats_free" #.(cl-swig-lispify "cv_floats_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_floats_count" #.(cl-swig-lispify "cv_floats_count" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_floats_add" #.(cl-swig-lispify "cv_floats_add" 'function)) :pointer
  (self :pointer)
  (val :float))

(cffi:defcfun ("cv_floats_get" #.(cl-swig-lispify "cv_floats_get" 'function)) :float
  (self :pointer)
  (i :int))

(cffi:defcfun ("cv_floats_data" #.(cl-swig-lispify "cv_floats_data" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_doubles_new" #.(cl-swig-lispify "cv_doubles_new" 'function)) :pointer)

(cffi:defcfun ("cv_doubles_new_with_data" #.(cl-swig-lispify "cv_doubles_new_with_data" 'function)) :pointer
  (size :int)
  (data :pointer))

(cffi:defcfun ("cv_doubles_free" #.(cl-swig-lispify "cv_doubles_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_doubles_count" #.(cl-swig-lispify "cv_doubles_count" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_doubles_add" #.(cl-swig-lispify "cv_doubles_add" 'function)) :pointer
  (self :pointer)
  (val :double))

(cffi:defcfun ("cv_doubles_get" #.(cl-swig-lispify "cv_doubles_get" 'function)) :double
  (self :pointer)
  (i :int))

(cffi:defcfun ("cv_doubles_data" #.(cl-swig-lispify "cv_doubles_data" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_size_new" #.(cl-swig-lispify "cv_size_new" 'function)) :pointer
  (w :float)
  (h :float))

(cffi:defcfun ("cv_size_copy" #.(cl-swig-lispify "cv_size_copy" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_size_free" #.(cl-swig-lispify "cv_size_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_size_width" #.(cl-swig-lispify "cv_size_width" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_size_height" #.(cl-swig-lispify "cv_size_height" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_scalar_new" #.(cl-swig-lispify "cv_scalar_new" 'function)) :pointer
  (a :double)
  (b :double)
  (c :double)
  (d :double))

(cffi:defcfun ("cv_scalar_copy" #.(cl-swig-lispify "cv_scalar_copy" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_scalar_free" #.(cl-swig-lispify "cv_scalar_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_scalar_values" #.(cl-swig-lispify "cv_scalar_values" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_point_new" #.(cl-swig-lispify "cv_point_new" 'function)) :pointer
  (x :float)
  (y :float))

(cffi:defcfun ("cv_point_copy" #.(cl-swig-lispify "cv_point_copy" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_point_free" #.(cl-swig-lispify "cv_point_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_point_x" #.(cl-swig-lispify "cv_point_x" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_point_y" #.(cl-swig-lispify "cv_point_y" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_points_new" #.(cl-swig-lispify "cv_points_new" 'function)) :pointer)

(cffi:defcfun ("cv_points_new_with_data" #.(cl-swig-lispify "cv_points_new_with_data" 'function)) :pointer
  (count :int)
  (data :pointer))

(cffi:defcfun ("cv_points_add" #.(cl-swig-lispify "cv_points_add" 'function)) :pointer
  (self :pointer)
  (point :pointer))

(cffi:defcfun ("cv_points_free" #.(cl-swig-lispify "cv_points_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_points_count" #.(cl-swig-lispify "cv_points_count" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_points_get" #.(cl-swig-lispify "cv_points_get" 'function)) :pointer
  (self :pointer)
  (idx :int))

(cffi:defcfun ("cv_rect_new" #.(cl-swig-lispify "cv_rect_new" 'function)) :pointer
  (x :float)
  (y :float)
  (w :float)
  (h :float))

(cffi:defcfun ("cv_rect_copy" #.(cl-swig-lispify "cv_rect_copy" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_rect_free" #.(cl-swig-lispify "cv_rect_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_rect_x" #.(cl-swig-lispify "cv_rect_x" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rect_y" #.(cl-swig-lispify "cv_rect_y" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rect_width" #.(cl-swig-lispify "cv_rect_width" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rect_height" #.(cl-swig-lispify "cv_rect_height" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_new" #.(cl-swig-lispify "cv_rotated_rect_new" 'function)) :pointer
  (x :float)
  (y :float)
  (width :float)
  (height :float)
  (angle :float))

(cffi:defcfun ("cv_rotated_rect_copy" #.(cl-swig-lispify "cv_rotated_rect_copy" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_free" #.(cl-swig-lispify "cv_rotated_rect_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_x" #.(cl-swig-lispify "cv_rotated_rect_x" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_y" #.(cl-swig-lispify "cv_rotated_rect_y" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_width" #.(cl-swig-lispify "cv_rotated_rect_width" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_height" #.(cl-swig-lispify "cv_rotated_rect_height" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_angle" #.(cl-swig-lispify "cv_rotated_rect_angle" 'function)) :float
  (self :pointer))

(cffi:defcfun ("cv_rotated_rect_points" #.(cl-swig-lispify "cv_rotated_rect_points" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_rotated_rects_new" #.(cl-swig-lispify "cv_rotated_rects_new" 'function)) :pointer)

(cffi:defcfun ("cv_rotated_rects_new_with_data" #.(cl-swig-lispify "cv_rotated_rects_new_with_data" 'function)) :pointer
  (count :int)
  (data :pointer))

(cffi:defcfun ("cv_rotated_rects_add" #.(cl-swig-lispify "cv_rotated_rects_add" 'function)) :pointer
  (self :pointer)
  (rect :pointer))

(cffi:defcfun ("cv_rotated_rects_free" #.(cl-swig-lispify "cv_rotated_rects_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_rotated_rects_count" #.(cl-swig-lispify "cv_rotated_rects_count" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_rotated_rects_get" #.(cl-swig-lispify "cv_rotated_rects_get" 'function)) :pointer
  (self :pointer)
  (idx :int))

(cl:defconstant #.(cl-swig-lispify "CV_8U" 'constant) 0)

(cl:defconstant #.(cl-swig-lispify "CV_8S" 'constant) 1)

(cl:defconstant #.(cl-swig-lispify "CV_16U" 'constant) 2)

(cl:defconstant #.(cl-swig-lispify "CV_16S" 'constant) 3)

(cl:defconstant #.(cl-swig-lispify "CV_32S" 'constant) 4)

(cl:defconstant #.(cl-swig-lispify "CV_32F" 'constant) 5)

(cl:defconstant #.(cl-swig-lispify "CV_64F" 'constant) 6)

(cl:defconstant #.(cl-swig-lispify "CV_16F" 'constant) 7)

(cffi:defcfun ("cv_mats_new" #.(cl-swig-lispify "cv_mats_new" 'function)) :pointer)

(cffi:defcfun ("cv_mats_new_with_data" #.(cl-swig-lispify "cv_mats_new_with_data" 'function)) :pointer
  (size :int)
  (data :pointer))

(cffi:defcfun ("cv_mats_free" #.(cl-swig-lispify "cv_mats_free" 'function)) :void
  (self :pointer))

(cffi:defcfun ("cv_mats_add" #.(cl-swig-lispify "cv_mats_add" 'function)) :pointer
  (self :pointer)
  (mat :pointer))

(cffi:defcfun ("cv_mats_count" #.(cl-swig-lispify "cv_mats_count" 'function)) :int
  (self :pointer))

(cffi:defcfun ("cv_mats_get" #.(cl-swig-lispify "cv_mats_get" 'function)) :pointer
  (self :pointer)
  (i :int))

(cffi:defcfun ("cv_make_type" #.(cl-swig-lispify "cv_make_type" 'function)) :int
  (depth :int)
  (channels :int))

(cffi:defcfun ("cv_type_depth" #.(cl-swig-lispify "cv_type_depth" 'function)) :int
  (type :int))

(cffi:defcfun ("cv_type_channels" #.(cl-swig-lispify "cv_type_channels" 'function)) :int
  (type :int))

(cffi:defcfun ("cv_mat_new" #.(cl-swig-lispify "cv_mat_new" 'function)) :pointer)

(cffi:defcfun ("cv_mat_new_with_scalar" #.(cl-swig-lispify "cv_mat_new_with_scalar" 'function)) :pointer
  (shape :pointer)
  (type :int)
  (scalar :pointer))

(cffi:defcfun ("cv_mat_new_with_bytes" #.(cl-swig-lispify "cv_mat_new_with_bytes" 'function)) :pointer
  (shape :pointer)
  (type :int)
  (bytes :pointer))

(cffi:defcfun ("cv_mat_copy" #.(cl-swig-lispify "cv_mat_copy" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_mat_free" #.(cl-swig-lispify "cv_mat_free" 'function)) :void
  (m :pointer))

(cffi:defcfun ("cv_mat_empty" #.(cl-swig-lispify "cv_mat_empty" 'function)) :bool
  (m :pointer))

(cffi:defcfun ("cv_mat_copy_to" #.(cl-swig-lispify "cv_mat_copy_to" 'function)) :bool
  (m :pointer)
  (dst :pointer))

(cffi:defcfun ("cv_mat_copy_to_with_mask" #.(cl-swig-lispify "cv_mat_copy_to_with_mask" 'function)) :bool
  (m :pointer)
  (dst :pointer)
  (mask :pointer))

(cffi:defcfun ("cv_mat_convert_to" #.(cl-swig-lispify "cv_mat_convert_to" 'function)) :bool
  (self :pointer)
  (dst :pointer)
  (type :int)
  (alpha :double)
  (beta :double))

(cffi:defcfun ("cv_mat_to_buffer" #.(cl-swig-lispify "cv_mat_to_buffer" 'function)) :pointer
  (m :pointer))

(cffi:defcfun ("cv_mat_patch_nans" #.(cl-swig-lispify "cv_mat_patch_nans" 'function)) :void
  (m :pointer)
  (val :double))

(cffi:defcfun ("cv_mat_mean" #.(cl-swig-lispify "cv_mat_mean" 'function)) :pointer
  (m :pointer))

(cffi:defcfun ("cv_mat_lut" #.(cl-swig-lispify "cv_mat_lut" 'function)) :bool
  (src :pointer)
  (lut :pointer)
  (dst :pointer))

(cffi:defcfun ("cv_mat_channels" #.(cl-swig-lispify "cv_mat_channels" 'function)) :int
  (m :pointer))

(cffi:defcfun ("cv_mat_depth" #.(cl-swig-lispify "cv_mat_depth" 'function)) :int
  (m :pointer))

(cffi:defcfun ("cv_mat_type" #.(cl-swig-lispify "cv_mat_type" 'function)) :int
  (m :pointer))

(cffi:defcfun ("cv_mat_step" #.(cl-swig-lispify "cv_mat_step" 'function)) :long
  (m :pointer))

(cffi:defcfun ("cv_mat_is_continuous" #.(cl-swig-lispify "cv_mat_is_continuous" 'function)) :bool
  (m :pointer))

(cffi:defcfun ("cv_mat_total" #.(cl-swig-lispify "cv_mat_total" 'function)) :long
  (m :pointer))

(cffi:defcfun ("cv_mat_dims" #.(cl-swig-lispify "cv_mat_dims" 'function)) :int
  (m :pointer))

(cffi:defcfun ("cv_mat_size" #.(cl-swig-lispify "cv_mat_size" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("cv_mat_rows" #.(cl-swig-lispify "cv_mat_rows" 'function)) :int
  (m :pointer))

(cffi:defcfun ("cv_mat_cols" #.(cl-swig-lispify "cv_mat_cols" 'function)) :int
  (m :pointer))

(cffi:defcfun ("cv_mat_reshape" #.(cl-swig-lispify "cv_mat_reshape" 'function)) :pointer
  (m :pointer)
  (cn :int)
  (shape :pointer))

(cffi:defcfun ("cv_mat_get_int" #.(cl-swig-lispify "cv_mat_get_int" 'function)) :int
  (m :pointer)
  (idx :pointer))

(cffi:defcfun ("cv_mat_get_double" #.(cl-swig-lispify "cv_mat_get_double" 'function)) :double
  (m :pointer)
  (idx :pointer))

(cffi:defcfun ("cv_mat_get_ptr" #.(cl-swig-lispify "cv_mat_get_ptr" 'function)) :pointer
  (m :pointer)
  (idx :pointer))

(cffi:defcfun ("cv_mat_set_int" #.(cl-swig-lispify "cv_mat_set_int" 'function)) :bool
  (m :pointer)
  (idx :pointer)
  (val :int))

(cffi:defcfun ("cv_mat_set_double" #.(cl-swig-lispify "cv_mat_set_double" 'function)) :bool
  (m :pointer)
  (idx :pointer)
  (val :double))

(cffi:defcfun ("cv_get_tick_count" #.(cl-swig-lispify "cv_get_tick_count" 'function)) :long)

(cffi:defcfun ("cv_get_tick_frequency" #.(cl-swig-lispify "cv_get_tick_frequency" 'function)) :double)

(cffi:defcenum #.(cl-swig-lispify "CvImreadModes" 'enumname)
	(#.(cl-swig-lispify "IMREAD_UNCHANGED" 'enumvalue :keyword) #.-1)
	(#.(cl-swig-lispify "IMREAD_GRAYSCALE" 'enumvalue :keyword) #.0)
	(#.(cl-swig-lispify "IMREAD_COLOR" 'enumvalue :keyword) #.1)
	(#.(cl-swig-lispify "IMREAD_ANYDEPTH" 'enumvalue :keyword) #.2)
	(#.(cl-swig-lispify "IMREAD_ANYCOLOR" 'enumvalue :keyword) #.4)
	(#.(cl-swig-lispify "IMREAD_LOAD_GDAL" 'enumvalue :keyword) #.8)
	(#.(cl-swig-lispify "IMREAD_REDUCED_GRAYSCALE_2" 'enumvalue :keyword) #.16)
	(#.(cl-swig-lispify "IMREAD_REDUCED_COLOR_2" 'enumvalue :keyword) #.17)
	(#.(cl-swig-lispify "IMREAD_REDUCED_GRAYSCALE_4" 'enumvalue :keyword) #.32)
	(#.(cl-swig-lispify "IMREAD_REDUCED_COLOR_4" 'enumvalue :keyword) #.33)
	(#.(cl-swig-lispify "IMREAD_REDUCED_GRAYSCALE_8" 'enumvalue :keyword) #.64)
	(#.(cl-swig-lispify "IMREAD_REDUCED_COLOR_8" 'enumvalue :keyword) #.65)
	(#.(cl-swig-lispify "IMREAD_IGNORE_ORIENTATION" 'enumvalue :keyword) #.128))

(cffi:defcfun ("cv_imread" #.(cl-swig-lispify "cv_imread" 'function)) :pointer
  (filename :string)
  (flags :int))

(cffi:defcfun ("cv_imdecode" #.(cl-swig-lispify "cv_imdecode" 'function)) :pointer
  (buf :string)
  (flags :int))

(cffi:defcfun ("cv_imwrite" #.(cl-swig-lispify "cv_imwrite" 'function)) :bool
  (filename :string)
  (img :pointer)
  (params :pointer))

(cffi:defcfun ("cv_imencode" #.(cl-swig-lispify "cv_imencode" 'function)) :pointer
  (file_ext :string)
  (img :pointer)
  (params :pointer))

(cffi:defcenum #.(cl-swig-lispify "CvLineTypes" 'enumname)
	(#.(cl-swig-lispify "FILLED" 'enumvalue :keyword) #.-1)
	(#.(cl-swig-lispify "LINE_4" 'enumvalue :keyword) #.4)
	(#.(cl-swig-lispify "LINE_8" 'enumvalue :keyword) #.8)
	(#.(cl-swig-lispify "LINE_AA" 'enumvalue :keyword) #.16))

(cffi:defcenum #.(cl-swig-lispify "CvHersheyFonts" 'enumname)
	(#.(cl-swig-lispify "FONT_HERSHEY_SIMPLEX" 'enumvalue :keyword) #.0)
	(#.(cl-swig-lispify "FONT_HERSHEY_PLAIN" 'enumvalue :keyword) #.1)
	(#.(cl-swig-lispify "FONT_HERSHEY_DUPLEX" 'enumvalue :keyword) #.2)
	(#.(cl-swig-lispify "FONT_HERSHEY_COMPLEX" 'enumvalue :keyword) #.3)
	(#.(cl-swig-lispify "FONT_HERSHEY_TRIPLEX" 'enumvalue :keyword) #.4)
	(#.(cl-swig-lispify "FONT_HERSHEY_COMPLEX_SMALL" 'enumvalue :keyword) #.5)
	(#.(cl-swig-lispify "FONT_HERSHEY_SCRIPT_SIMPLEX" 'enumvalue :keyword) #.6)
	(#.(cl-swig-lispify "FONT_HERSHEY_SCRIPT_COMPLEX" 'enumvalue :keyword) #.7)
	(#.(cl-swig-lispify "FONT_ITALIC" 'enumvalue :keyword) #.16))

(cffi:defcfun ("cv_cvt_color" #.(cl-swig-lispify "cv_cvt_color" 'function)) :bool
  (src :pointer)
  (dst :pointer)
  (code :int)
  (dst_cn :int))

(cffi:defcfun ("cv_blur" #.(cl-swig-lispify "cv_blur" 'function)) :bool
  (src :pointer)
  (dst :pointer)
  (ksize :pointer)
  (anchor :pointer)
  (border_type :int))

(cffi:defcfun ("cv_resize" #.(cl-swig-lispify "cv_resize" 'function)) :bool
  (src :pointer)
  (dst :pointer)
  (dsize :pointer)
  (fx :double)
  (fy :double)
  (interpolation :int))

(cffi:defcfun ("cv_line" #.(cl-swig-lispify "cv_line" 'function)) :void
  (img :pointer)
  (pt1 :pointer)
  (pt2 :pointer)
  (color :pointer)
  (thickness :int)
  (line_type :int)
  (shift :int))

(cffi:defcfun ("cv_arrowed_line" #.(cl-swig-lispify "cv_arrowed_line" 'function)) :void
  (img :pointer)
  (pt1 :pointer)
  (pt2 :pointer)
  (color :pointer)
  (thickness :int)
  (line_type :int)
  (shift :int)
  (tipLength :double))

(cffi:defcfun ("cv_circle" #.(cl-swig-lispify "cv_circle" 'function)) :void
  (img :pointer)
  (center :pointer)
  (radius :int)
  (color :pointer)
  (thickness :int)
  (line_type :int)
  (shift :int))

(cffi:defcfun ("cv_ellipse" #.(cl-swig-lispify "cv_ellipse" 'function)) :void
  (img :pointer)
  (center :pointer)
  (axes :pointer)
  (angle :double)
  (start_angle :double)
  (end_angle :double)
  (color :pointer)
  (thickness :int)
  (line_type :int)
  (shift :int))

(cffi:defcfun ("cv_rectangle" #.(cl-swig-lispify "cv_rectangle" 'function)) :void
  (img :pointer)
  (rect :pointer)
  (color :pointer)
  (thickness :int)
  (lineType :int)
  (shift :int))

(cffi:defcfun ("cv_get_text_size" #.(cl-swig-lispify "cv_get_text_size" 'function)) :pointer
  (text :string)
  (font_face :int)
  (font_scale :double)
  (thickness :int)
  (base_line :pointer))

(cffi:defcfun ("cv_put_text" #.(cl-swig-lispify "cv_put_text" 'function)) :bool
  (img :pointer)
  (text :string)
  (org :pointer)
  (font_face :int)
  (font_scale :double)
  (color :pointer)
  (thickness :int)
  (line_type :int)
  (bottom_left_origin :bool))

(cffi:defcfun ("cv_named_window" #.(cl-swig-lispify "cv_named_window" 'function)) :void
  (winname :string)
  (flags :int))

(cffi:defcfun ("cv_destroy_window" #.(cl-swig-lispify "cv_destroy_window" 'function)) :void
  (winname :string))

(cffi:defcfun ("cv_destroy_all_windows" #.(cl-swig-lispify "cv_destroy_all_windows" 'function)) :void)

(cffi:defcfun ("cv_imshow" #.(cl-swig-lispify "cv_imshow" 'function)) :bool
  (winname :string)
  (mat :pointer))

(cffi:defcfun ("cv_get_window_property" #.(cl-swig-lispify "cv_get_window_property" 'function)) :double
  (winname :string)
  (flag :int))

(cffi:defcfun ("cv_set_window_property" #.(cl-swig-lispify "cv_set_window_property" 'function)) :void
  (winname :string)
  (flag :int)
  (value :double))

(cffi:defcfun ("cv_set_window_title" #.(cl-swig-lispify "cv_set_window_title" 'function)) :void
  (winname :string)
  (title :string))

(cffi:defcfun ("cv_wait_key" #.(cl-swig-lispify "cv_wait_key" 'function)) :int
  (delay :int))

(cffi:defcfun ("cv_move_window" #.(cl-swig-lispify "cv_move_window" 'function)) :void
  (winname :string)
  (x :int)
  (y :int))

(cffi:defcfun ("cv_resize_window" #.(cl-swig-lispify "cv_resize_window" 'function)) :void
  (winname :string)
  (width :int)
  (height :int))

(cffi:defcenum #.(cl-swig-lispify "CvVideoCaptureAPIs" 'enumname)
	(#.(cl-swig-lispify "CAP_ANY" 'enumvalue :keyword) #.0)
	(#.(cl-swig-lispify "CAP_VFW" 'enumvalue :keyword) #.200)
	(#.(cl-swig-lispify "CAP_V4L" 'enumvalue :keyword) #.200)
	(#.(cl-swig-lispify "CAP_V4L2" 'enumvalue :keyword) #.200)
	(#.(cl-swig-lispify "CAP_FIREWIRE" 'enumvalue :keyword) #.300)
	(#.(cl-swig-lispify "CAP_FIREWARE" 'enumvalue :keyword) #.300)
	(#.(cl-swig-lispify "CAP_IEEE1394" 'enumvalue :keyword) #.300)
	(#.(cl-swig-lispify "CAP_DC1394" 'enumvalue :keyword) #.300)
	(#.(cl-swig-lispify "CAP_CMU1394" 'enumvalue :keyword) #.300)
	(#.(cl-swig-lispify "CAP_QT" 'enumvalue :keyword) #.500)
	(#.(cl-swig-lispify "CAP_UNICAP" 'enumvalue :keyword) #.600)
	(#.(cl-swig-lispify "CAP_DSHOW" 'enumvalue :keyword) #.700)
	(#.(cl-swig-lispify "CAP_PVAPI" 'enumvalue :keyword) #.800)
	(#.(cl-swig-lispify "CAP_OPENNI" 'enumvalue :keyword) #.900)
	(#.(cl-swig-lispify "CAP_OPENNI_ASUS" 'enumvalue :keyword) #.910)
	(#.(cl-swig-lispify "CAP_ANDROID" 'enumvalue :keyword) #.1000)
	(#.(cl-swig-lispify "CAP_XIAPI" 'enumvalue :keyword) #.1100)
	(#.(cl-swig-lispify "CAP_AVFOUNDATION" 'enumvalue :keyword) #.1200)
	(#.(cl-swig-lispify "CAP_GIGANETIX" 'enumvalue :keyword) #.1300)
	(#.(cl-swig-lispify "CAP_MSMF" 'enumvalue :keyword) #.1400)
	(#.(cl-swig-lispify "CAP_WINRT" 'enumvalue :keyword) #.1410)
	(#.(cl-swig-lispify "CAP_INTELPERC" 'enumvalue :keyword) #.1500)
	(#.(cl-swig-lispify "CAP_OPENNI2" 'enumvalue :keyword) #.1600)
	(#.(cl-swig-lispify "CAP_OPENNI2_ASUS" 'enumvalue :keyword) #.1610)
	(#.(cl-swig-lispify "CAP_GPHOTO2" 'enumvalue :keyword) #.1700)
	(#.(cl-swig-lispify "CAP_GSTREAMER" 'enumvalue :keyword) #.1800)
	(#.(cl-swig-lispify "CAP_FFMPEG" 'enumvalue :keyword) #.1900)
	(#.(cl-swig-lispify "CAP_IMAGES" 'enumvalue :keyword) #.2000)
	(#.(cl-swig-lispify "CAP_ARAVIS" 'enumvalue :keyword) #.2100)
	(#.(cl-swig-lispify "CAP_OPENCV_MJPEG" 'enumvalue :keyword) #.2200)
	(#.(cl-swig-lispify "CAP_INTEL_MFX" 'enumvalue :keyword) #.2300)
	(#.(cl-swig-lispify "CAP_XINE" 'enumvalue :keyword) #.2400))

(cffi:defcfun ("cv_video_capture_new" #.(cl-swig-lispify "cv_video_capture_new" 'function)) :pointer)

(cffi:defcfun ("cv_video_capture_free" #.(cl-swig-lispify "cv_video_capture_free" 'function)) :void
  (v :pointer))

(cffi:defcfun ("cv_video_capture_open_uri" #.(cl-swig-lispify "cv_video_capture_open_uri" 'function)) :bool
  (v :pointer)
  (uri :string)
  (api_preference :int))

(cffi:defcfun ("cv_video_capture_open_device" #.(cl-swig-lispify "cv_video_capture_open_device" 'function)) :bool
  (v :pointer)
  (device :int)
  (api_preference :int))

(cffi:defcfun ("cv_video_capture_set" #.(cl-swig-lispify "cv_video_capture_set" 'function)) :void
  (v :pointer)
  (prop :int)
  (param :double))

(cffi:defcfun ("cv_video_capture_get" #.(cl-swig-lispify "cv_video_capture_get" 'function)) :double
  (v :pointer)
  (prop :int))

(cffi:defcfun ("cv_video_capture_is_opened" #.(cl-swig-lispify "cv_video_capture_is_opened" 'function)) :bool
  (v :pointer))

(cffi:defcfun ("cv_video_capture_read" #.(cl-swig-lispify "cv_video_capture_read" 'function)) :bool
  (v :pointer)
  (buf :pointer))

(cffi:defcfun ("cv_video_capture_grab" #.(cl-swig-lispify "cv_video_capture_grab" 'function)) :bool
  (v :pointer))

(cffi:defcfun ("cv_video_capture_retrieve" #.(cl-swig-lispify "cv_video_capture_retrieve" 'function)) :bool
  (v :pointer)
  (buf :pointer)
  (flag :int))

(cffi:defcfun ("cv_video_writer_new" #.(cl-swig-lispify "cv_video_writer_new" 'function)) :pointer)

(cffi:defcfun ("cv_video_writer_free" #.(cl-swig-lispify "cv_video_writer_free" 'function)) :void
  (vw :pointer))

(cffi:defcfun ("cv_video_writer_fourcc" #.(cl-swig-lispify "cv_video_writer_fourcc" 'function)) :int
  (c1 :char)
  (c2 :char)
  (c3 :char)
  (c4 :char))

(cffi:defcfun ("cv_video_writer_open" #.(cl-swig-lispify "cv_video_writer_open" 'function)) :bool
  (vw :pointer)
  (name :string)
  (fourcc :int)
  (fps :double)
  (size :pointer)
  (isColor :bool))

(cffi:defcfun ("cv_video_writer_is_opened" #.(cl-swig-lispify "cv_video_writer_is_opened" 'function)) :bool
  (vw :pointer))

(cffi:defcfun ("cv_video_writer_write" #.(cl-swig-lispify "cv_video_writer_write" 'function)) :bool
  (vw :pointer)
  (img :pointer))

(cffi:defcfun ("cv_dnn_read_net" #.(cl-swig-lispify "cv_dnn_read_net" 'function)) :pointer
  (model :string)
  (config :string)
  (framework :string))

(cffi:defcfun ("cv_dnn_net_free" #.(cl-swig-lispify "cv_dnn_net_free" 'function)) :void
  (net :pointer))

(cffi:defcfun ("cv_dnn_net_empty" #.(cl-swig-lispify "cv_dnn_net_empty" 'function)) :bool
  (net :pointer))

(cffi:defcfun ("cv_dnn_net_set_input" #.(cl-swig-lispify "cv_dnn_net_set_input" 'function)) :bool
  (net :pointer)
  (blob :pointer)
  (name :string)
  (scale_factor :double)
  (mean :pointer))

(cffi:defcfun ("cv_dnn_net_forward" #.(cl-swig-lispify "cv_dnn_net_forward" 'function)) :bool
  (net :pointer)
  (output_name :string)
  (output_blob :pointer))

(cffi:defcfun ("cv_dnn_net_forward_layers" #.(cl-swig-lispify "cv_dnn_net_forward_layers" 'function)) :bool
  (net :pointer)
  (layer_names :pointer)
  (out_blobs :pointer))

(cffi:defcfun ("cv_dnn_net_set_preferable_backend" #.(cl-swig-lispify "cv_dnn_net_set_preferable_backend" 'function)) :void
  (net :pointer)
  (backend :int))

(cffi:defcfun ("cv_dnn_net_set_preferable_target" #.(cl-swig-lispify "cv_dnn_net_set_preferable_target" 'function)) :void
  (net :pointer)
  (target :int))

(cffi:defcfun ("cv_dnn_net_get_perf_profile" #.(cl-swig-lispify "cv_dnn_net_get_perf_profile" 'function)) :long
  (net :pointer)
  (out_layers :pointer))

(cffi:defcfun ("cv_dnn_blob_from_images" #.(cl-swig-lispify "cv_dnn_blob_from_images" 'function)) :bool
  (images :pointer)
  (out_blob :pointer)
  (scale_factor :double)
  (size :pointer)
  (mean :pointer)
  (swap_rb :bool)
  (crop :bool)
  (depth :int))

(cffi:defcfun ("cv_dnn_net_get_layer_names" #.(cl-swig-lispify "cv_dnn_net_get_layer_names" 'function)) :pointer
  (net :pointer))

(cffi:defcfun ("cv_dnn_net_get_layer" #.(cl-swig-lispify "cv_dnn_net_get_layer" 'function)) :pointer
  (net :pointer)
  (layerId :int))

(cffi:defcfun ("cv_dnn_layer_free" #.(cl-swig-lispify "cv_dnn_layer_free" 'function)) :void
  (layer :pointer))

(cffi:defcfun ("cv_dnn_layer_input_name_to_index" #.(cl-swig-lispify "cv_dnn_layer_input_name_to_index" 'function)) :int
  (layer :pointer)
  (name :string))

(cffi:defcfun ("cv_dnn_layer_output_name_to_index" #.(cl-swig-lispify "cv_dnn_layer_output_name_to_index" 'function)) :int
  (layer :pointer)
  (name :string))

(cffi:defcfun ("cv_dnn_layer_name" #.(cl-swig-lispify "cv_dnn_layer_name" 'function)) :string
  (layer :pointer))

(cffi:defcfun ("cv_dnn_layer_type" #.(cl-swig-lispify "cv_dnn_layer_type" 'function)) :string
  (layer :pointer))

(cffi:defcfun ("cv_dnn_nms_boxes" #.(cl-swig-lispify "cv_dnn_nms_boxes" 'function)) :pointer
  (bboxes :pointer)
  (scores :pointer)
  (score_threshold :float)
  (nms_threshold :float)
  (eta :float)
  (top_k :int))


